repo_url: https://github.com/Interacao-Humano-Computador/2026.1-Grupo06
repo_name: 2026.1-Grupo06
site_url: https://interacao-humano-computador.github.io/2026.1-Grupo06/

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox

site_name: Serviços de Matrícula DF

nav:
  - Home: index.md

  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md

  - Reuniões:
      - Heatmap: reunioes/heatmap.md
      - Reunião 1: reunioes/reuniao_1.md

  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Sites avaliados: planejamento/sites-avaliados.md
      - Site escolhido: planejamento/site-escolhido.md
      - Processo design: planejamento/processo-design.md
      
      
  - Análise de Requisitos:
      - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md

      - Perfil de Usuário:
          - Transferência Escolar: analise-de-requisitos/perfis/perfil-transferencia-matricula.md
          - Matricula PEBI: analise-de-requisitos/perfis/perfil-matricula-PEBI.md
          - Ensino especial: analise-de-requisitos/perfis/perfil-servico-especial.md
          - Creche: analise-de-requisitos/perfis/perfil-creches.md
          - Painel Educacional: analise-de-requisitos/perfis/Perfil-painel-educacional.md
          - Atendimento Domiciliar: analise-de-requisitos/perfis/atendimento-domiciliar.md
      - Personas:
          - Geral: analise-de-requisitos/personas/personas.md
          - Painel Educacional: analise-de-requisitos/personas/persona-painel-educacional.md
        

      - Cenarios: analise-de-requisitos/cenarios/cenarios.md

      - Analise de Tarefas:
          - Transferência Escolar: analise-de-requisitos/analise-de-tarefas/transferencia-matricula.md
          - Matricula PEBI: analise-de-requisitos/analise-de-tarefas/Matricula-PEBI.md
          - Creche: analise-de-requisitos/analise-de-tarefas/analise-creche.md 
  - Verificação:
      - Verificação do Grupo:
          - Etapa 1:
              - Planejamento da Verificação da Etapa 1: verificacao/grupo/etapa1/planejamento-verificacao-etapa1-grupo.md
              - Resultado da Verificação da Etapa 1: verificacao/grupo/etapa1/resultado-verificacao-etapa1-grupo.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
  favicon: assets/logogdf.png
  logo: assets/logogdf.png
